### PR TITLE
Uploaded logos to assets/logos

### PR DESCRIPTION
**Pull request by Anudeep-313**
- created separate directory for cogs.
- PTAL!!

### CODE REVIEW

**Comment by STBoyden** [comment]
Hi @Anudeep-313, thank you for creating the PR. As I mentioned in the issue, could you provide us with SVGs too? As well as full rights to the logo you have designed?

**Review by STBoyden — CHANGES_REQUESTED** [review]
Please take a look at my previous comment :)

**Comment by Anudeep-313** [comment]
I am working on it, i'll try to provide the logos in SVG format at the earliest possible.

**Comment by STBoyden** [comment]
> I am working on it, i'll try to provide the logos in SVG format at the earliest possible.

Great, thank you 😄

**Comment by STBoyden** [comment]
Yeah that's fine, don't worry. Take as long as you need.

**Comment by Anudeep-313** [comment]
I have uploaded the logos in SVG format, Please take a look.

**Review by STBoyden — CHANGES_REQUESTED** [review]
All the SVGs seem to just be including the PNGs rather than the original vector shapes. If you have the original EPS files at this point, you should be able to export directly as SVG?

**Comment by STBoyden** [comment]
@Anudeep-313 Hi, can you please take a look at the previous comments :)

**Comment by Anudeep-313** [comment]
> All the SVGs seem to just be including the PNGs rather than the original vector shapes. If you have the original EPS files at this point, you should be able to export directly as SVG?
> 
> Sorry, I'm not trying to be fussy, it's just that a proper scalable image would be really useful for the website and other needs.

Sorry for the late reply, I was busy with some other stuff.
I don't have EPS files right now......I understand what your trying to say, I'll try and provide the original vector graphics i.e. the logos in SVG format anytime before December .

**Comment by STBoyden** [comment]
> > All the SVGs seem to just be including the PNGs rather than the original vector shapes. If you have the original EPS files at this point, you should be able to export directly as SVG?
> > Sorry, I'm not trying to be fussy, it's just that a proper scalable image would be really useful for the website and other needs.
> 
> Sorry for the late reply, I was busy with some other stuff. I don't have EPS files right now......I understand what your trying to say, I'll try and provide the original vector graphics i.e. the logos in SVG format anytime before December .

Thank you very much, take your time with this. Sorry that we couldn't get this merged before the end of Hacktoberfest.

**Comment by STBoyden** [comment]
@Anudeep-313 Any updates so far?

**Comment by Anudeep-313** [comment]
> @Anudeep-313 Any updates so far?

**Comment by Anudeep-313** [comment]
> @Anudeep-313 Any updates so far?

Imma do it for sure..... but I'm not certain about date.

**Comment by STBoyden** [comment]
Sorry, it's been a month since the last update from you. I'm going to close this PR for the time being. If you manage to recover the files, please re-open the PR.

**Pull request closed without merging**
