### PR TITLE
gRPC re-implementation

### PR DESCRIPTION
**Pull request by STBoyden**
Self-explanatory PR title. 

This is a PR to track the [`gprc-rewrite` branch](https://github.com/Authentura/codectrl/tree/gprc-rewrite).

This will be merged when the major language loggers (Rust, C++, Python, PHP) are updated to conform to the gRPC rewrite branch.

### CODE REVIEW

**Comment by z9fr** [comment]
> @svmorris @z9fr Are you able to start on the Python and PHP client implementations? The protobuf files are in [here](https://github.com/Authentura/codectrl-protobuf-specifications).

sure, ill start to working on it soon.

**Comment by STBoyden** [comment]
# Finished core logger re-implementations

- [x] Rust
- [ ] C++
- [ ] Python
- [ ] PHP

**Comment by STBoyden** [comment]
> This will be merged when the major language loggers (Rust, C++, Python, PHP) are updated to conform to the gRPC rewrite branch.

Might just merge this now, the `release` branch will still be available without the breaking gRPC changes.

**Comment by STBoyden** [comment]
Merging. Regardless of the status of core language loggers. `release` will stay untouched.

**Pull request merged**
